/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    CreateBucketDialog: typeof import('./src/components/kv/dialogs/CreateBucketDialog.vue')['default']
    DownloadSelect: typeof import('./src/components/kv/Tools/DownloadSelect.vue')['default']
    KvMain: typeof import('./src/components/kv/KvMain.vue')['default']
    KvManager: typeof import('./src/components/kv/KvMergeCheck.vue')['default']
    KvMergeCheck: typeof import('./src/components/kv/KvMergeCheck.vue')['default']
    LangSelect: typeof import('./src/components/kv/LangSelect.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NotFound: typeof import('./src/components/pages/NotFound.vue')['default']
    NP: typeof import('naive-ui')['NP']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTable: typeof import('naive-ui')['NTable']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    RootProvider: typeof import('./src/components/providers/RootProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderBar: typeof import('./src/components/kv/SiderBar.vue')['default']
    Toggle: typeof import('./src/components/ui/toggle/Toggle.vue')['default']
    ToggleGroup: typeof import('./src/components/ui/toggle-group/ToggleGroup.vue')['default']
    ToggleGroupItem: typeof import('./src/components/ui/toggle-group/ToggleGroupItem.vue')['default']
    ToolSider: typeof import('./src/components/kv/ToolSider.vue')['default']
    UploadMerge: typeof import('./src/components/kv/Tools/UploadMerge.vue')['default']
    UploadNewLang: typeof import('./src/components/kv/Tools/UploadNewLang.vue')['default']
    VxeButton: typeof import('vxe-table/es/button/index.js')['VxeButton']
    VxeColumn: typeof import('vxe-table/es/column/index.js')['VxeColumn']
    VxeInput: typeof import('vxe-table/es/input/index.js')['VxeInput']
    VxeOption: typeof import('vxe-table/es/option/index.js')['VxeOption']
    VxeSelect: typeof import('vxe-table/es/select/index.js')['VxeSelect']
    VxeTable: typeof import('vxe-table/es/table/index.js')['VxeTable']
  }
}
