# Code generated by Lark OpenAPI.

import json
from app.api.deps import SessionDep
from app.common.config import Config
from app.models.response import ResponseBase
import app.utils.feishu_helper as feishu_helper
from fastapi import APIRouter
import lark_oapi as lark
from lark_oapi.api.translation.v1 import *

router = APIRouter()


@router.post("/trans_text", response_model=ResponseBase)
def trans_text(source_language, text, target_language):
    # 发起请求
    response: TranslateTextResponse = feishu_helper.text_translate(
        source_language, text, target_language
    )

    # 处理失败返回
    if not response.success():
        lark.logger.error(
            f"client.translation.v1.text.translate failed, code: {response.code}, msg: {response.msg}, log_id: {response.get_log_id()}"
        )
        return ResponseBase(code=response.code, data={"msg": response.msg})
    res_data = json.loads(lark.JSON.marshal(response.data, indent=4))
    return ResponseBase(code=response.code, data=res_data)
