// This file is auto-generated by @hey-api/openapi-ts

export const $Body_kv_upload_file = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_kv-upload_file'
} as const;

export const $BucketFile = {
    properties: {
        bucketName: {
            type: 'string',
            title: 'Bucketname'
        },
        relativePath: {
            type: 'string',
            title: 'Relativepath'
        }
    },
    type: 'object',
    required: ['bucketName', 'relativePath'],
    title: 'BucketFile'
} as const;

export const $BucketItemBase = {
    properties: {
        bucketName: {
            type: 'string',
            title: 'Bucketname'
        }
    },
    type: 'object',
    required: ['bucketName'],
    title: 'BucketItemBase'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $KvItem = {
    properties: {
        bucketName: {
            type: 'string',
            title: 'Bucketname'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        value: {
            type: 'string',
            title: 'Value'
        }
    },
    type: 'object',
    required: ['bucketName', 'key', 'value'],
    title: 'KvItem'
} as const;

export const $KvItemBase = {
    properties: {
        bucketName: {
            type: 'string',
            title: 'Bucketname'
        },
        key: {
            type: 'string',
            title: 'Key'
        }
    },
    type: 'object',
    required: ['bucketName', 'key'],
    title: 'KvItemBase'
} as const;

export const $RenameBucketItem = {
    properties: {
        bucketName: {
            type: 'string',
            title: 'Bucketname'
        },
        newBucketName: {
            type: 'string',
            title: 'Newbucketname'
        }
    },
    type: 'object',
    required: ['bucketName', 'newBucketName'],
    title: 'RenameBucketItem'
} as const;

export const $ResponseBase = {
    properties: {
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type',
            default: 'response'
        },
        code: {
            type: 'integer',
            title: 'Code',
            default: 0
        },
        data: {
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ResponseBase'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;