// This file is auto-generated by @hey-api/openapi-ts

export type Body_kv_upload_file = {
    file: (Blob | File);
};

export type BucketFile = {
    bucketName: string;
    relativePath: string;
};

export type BucketItemBase = {
    bucketName: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type KvItem = {
    bucketName: string;
    key: string;
    value: string;
};

export type KvItemBase = {
    bucketName: string;
    key: string;
};

export type RenameBucketItem = {
    bucketName: string;
    newBucketName: string;
};

export type ResponseBase = {
    type?: string | null;
    code?: number;
    data: unknown;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type $OpenApiTs = {
    '/api/v1/kv/get_kv_data': {
        get: {
            req: {
                requestBody: BucketItemBase;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/get_kv_record': {
        get: {
            req: {
                requestBody: KvItemBase;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/update_kv': {
        post: {
            req: {
                requestBody: KvItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/delete_kv': {
        post: {
            req: {
                requestBody: KvItemBase;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/get_bucket_list': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
            };
        };
    };
    '/api/v1/kv/create_bucket': {
        post: {
            req: {
                requestBody: BucketItemBase;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/rename_bucket': {
        post: {
            req: {
                requestBody: RenameBucketItem;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/delete_bucket': {
        post: {
            req: {
                requestBody: BucketItemBase;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/upload-file': {
        post: {
            req: {
                formData: Body_kv_upload_file;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/download-file': {
        get: {
            req: {
                requestBody: BucketFile;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/common/get_version': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
            };
        };
    };
    '/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: string;
            };
        };
    };
};