// This file is auto-generated by @hey-api/openapi-ts

export type Body_kv_upload_file = {
    file: (Blob | File);
};

export type BucketFile = {
    bucketName: string;
    relativePath: string;
};

export type BucketItemBase = {
    bucketName: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type KvItem = {
    bucketName: string;
    key: string;
    value: string;
};

export type KvItemBase = {
    bucketName: string;
    key: string;
};

export type RenameBucketItem = {
    bucketName: string;
    newBucketName: string;
};

export type ResponseBase = {
    type?: string | null;
    code?: number;
    data: unknown;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type KvGetKvDataData = {
    requestBody: BucketItemBase;
};

export type KvGetKvDataResponse = ResponseBase;

export type KvGetKvRecordData = {
    requestBody: KvItemBase;
};

export type KvGetKvRecordResponse = ResponseBase;

export type KvUpdateKvData = {
    requestBody: KvItem;
};

export type KvUpdateKvResponse = ResponseBase;

export type KvDeleteKvData = {
    requestBody: KvItemBase;
};

export type KvDeleteKvResponse = ResponseBase;

export type KvGetBucketListResponse = ResponseBase;

export type KvCreateBucketData = {
    requestBody: BucketItemBase;
};

export type KvCreateBucketResponse = ResponseBase;

export type KvCreateBucket1Data = {
    requestBody: RenameBucketItem;
};

export type KvCreateBucket1Response = ResponseBase;

export type KvDeleteBucketData = {
    requestBody: BucketItemBase;
};

export type KvDeleteBucketResponse = ResponseBase;

export type KvUploadFileData = {
    formData: Body_kv_upload_file;
};

export type KvUploadFileResponse = unknown;

export type KvDownloadFileData = {
    requestBody: BucketFile;
};

export type KvDownloadFileResponse = unknown;

export type IndexHomeResponse = string;

export type $OpenApiTs = {
    '/api/v1/kv/get_kv_data': {
        get: {
            req: KvGetKvDataData;
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/get_kv_record': {
        get: {
            req: KvGetKvRecordData;
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/update_kv': {
        post: {
            req: KvUpdateKvData;
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/delete_kv': {
        post: {
            req: KvDeleteKvData;
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/get_bucket_list': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
            };
        };
    };
    '/api/v1/kv/create_bucket': {
        post: {
            req: KvCreateBucketData;
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/rename_bucket': {
        post: {
            req: KvCreateBucket1Data;
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/delete_bucket': {
        post: {
            req: KvDeleteBucketData;
            res: {
                /**
                 * Successful Response
                 */
                200: ResponseBase;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/upload-file': {
        post: {
            req: KvUploadFileData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/kv/download-file': {
        get: {
            req: KvDownloadFileData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: string;
            };
        };
    };
};